### ISSUE TITLE
请问云数据库结构是什么样的?

### ISSUE THREAD

**Issue by q409640976** [rhinoc/Resser#1]
搭建上,发现没有数据库,另外是不是云数据库?

**Comment by rhinoc** [comment]
![Uploading image.png…]()

**Comment by rhinoc** [comment]
使用的是云数据库，打包的话，数据库没有办法显示在源码中。用户的数据库结构很简单，只记录了订阅列表，结构如图：
![image](https://user-images.githubusercontent.com/9894617/67636236-96b55980-f909-11e9-8f4f-581597e5b81b.png)

**Comment by q409640976** [comment]
谢谢
